[env:hawk_esp32s2_oled_v1]
extends = esp32s2_base
board = esp32-s2-saola-1
; upload_protocol = esp-builtin

build_flags = 
  ${esp32s2_base.build_flags} -D PRIVATE_HW -I variants/hawk_esp32s2_oled_v1
  -DGPS_POWER_TOGGLE ; comment this line to disable triple press function on the user button to turn off gps entirely.
